# Generated by Django 5.1.2 on 2024-10-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_ms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chapter',
            field=models.FileField(default='good', upload_to=''),
            preserve_default=False,
        ),
    ]
